# Generated by Django 4.2 on 2023-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='country',
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
